spring:
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true # 웹 요청이 1로 왔을 때 0으로 보정

  datasource:
    url: jdbc:h2:mem:haerolog
    username: sa
    password:
    driver-class-name: org.h2.Driver