spring:
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:haerolog
    username: sa
    password:
    driver-class-name: org.h2.Driver