### 로그인

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "password2"
}

###
GET {{host}}/foo
Content-Type: application/json
Authorization: 123

###
GET http://localhost:8080/bar?acc=1