### 로그인

POST {{host}}/api/v1/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "password1"
}

### JWT 방식 로그인
POST http://localhost:8081/api/v1/login/jwt
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "password1"
}


### 인증 페이지 요청
GET {{host}}/foo
Content-Type: application/json
Cookie: SESSION=d8033f30-65e8-40e6-a4d0-8af56e4145cb



###
GET http://localhost:8080/bar?acc=1